"""Add title and active columns to transcripts

Revision ID: 01854bfeb8ca
Revises: 17a3fcb26787
Create Date: 2025-09-19 17:34:07.338248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01854bfeb8ca'
down_revision: Union[str, Sequence[str], None] = '17a3fcb26787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('title', sa.String(length=255), nullable=True))
    # Add active column as nullable first
    op.add_column('transcripts', sa.Column('active', sa.Boolean(), nullable=True))
    # Update existing records to set active = True
    op.execute("UPDATE transcripts SET active = TRUE WHERE active IS NULL")
    # Now make the column NOT NULL
    op.alter_column('transcripts', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'active')
    op.drop_column('transcripts', 'title')
    # ### end Alembic commands ###
