"""Auto-generated migration from production schema

Revision ID: 1e4c2cef4eb8
Revises: 4d569edea0cb
Create Date: 2025-09-21 23:20:18.249083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4c2cef4eb8'
down_revision: Union[str, Sequence[str], None] = '4d569edea0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
