"""Auto-generated migration from production schema

Revision ID: 3fab367e6faa
Revises: 0ec949eaf0e8
Create Date: 2025-09-22 19:36:18.327497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fab367e6faa'
down_revision: Union[str, Sequence[str], None] = '0ec949eaf0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
