"""Auto-generated migration from production schema

Revision ID: e230fdfe2d09
Revises: 40ea08fcc8aa
Create Date: 2025-09-23 21:12:46.083399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e230fdfe2d09'
down_revision: Union[str, Sequence[str], None] = '40ea08fcc8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
