"""Remove provide_link_to_searcher field from transcripts

Revision ID: ebdbba76ac88
Revises: 1e4c2cef4eb8
Create Date: 2025-09-22 17:35:44.068127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdbba76ac88'
down_revision: Union[str, Sequence[str], None] = '1e4c2cef4eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'provide_link_to_searcher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('provide_link_to_searcher', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
